version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentax
    volumes:
      - pgdata:/data/postgres
    app:
    build: .
    container_name: rentax
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
    	- database
    depends_on:
	    - database


volumes:
  pgdata:
    driver: local
